import '@/component/style/global.scss'
import type { Metadata } from 'next'
import { roboto } from '@/component/fonts/fonts'

export const metadata: Metadata = {
  title: 'Belaundry Admin',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={roboto.className}>{children}</body>
    </html>
  )
}
